In [1]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [2]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('D06_HW-1.npz',array1,array2)

In [15]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array(range(20))
load_data = np.load('D06_HW-1.npz')
print(load_data.files)
a = load_data['arr_0']
b = load_data['arr_1']
np.savez('D06_HW-2.npz',a,b,array3)
print(a)
print(b)
print(array3)

['arr_0', 'arr_1']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
load_data2 = np.load('D06_HW-2.npz')
print(load_data2['arr_0'])
print(load_data2['arr_1'])
print(load_data2['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
